### ISSUE TITLE
Remove SerializationHelper from MessageRouter

### ISSUE THREAD

**Issue by pblasucci** [QuickenLoans/MessageRouter#11]
MessageRouter doesn't really know or care about serialization. This helper, though potentially useful, could probably find a better home elsewhere.

**Comment by johnbfair** [comment]
The idea behind SerializationHelper is that it's necessary to determine what type of object we've received from the caller.  I'm sure there's a better (non-XML-specific) way to handle this though! :+1:

**Comment by pblasucci** [comment]
Are you sure? Currently this functionality isn't used by MessageRouter.

**Comment by johnbfair** [comment]
No.....?  :hushed:

**Comment by pblasucci** [comment]
Sí. MessageRouter works completely at the CLR-type level. No strings at all.

**Comment by pblasucci** [comment]
This has been attempted in PR #16
