### ISSUE TITLE
Consider breaking up MessagerRouter.Reflection library

### ISSUE THREAD

**Issue by pblasucci** [QuickenLoans/MessageRouter#15]
Perhaps we should put the bits which are specific to the function of the router _into_ the MessageRouter library, and move the remaining bits into the SDK? On a related note, rather than a C#-specific SDK, perhaps it should be a general-purpose SDK, which makes a guarantee that (among other things) it will provide a first-class experience slotting the router into a C# (or VB.NET) project?

**Comment by johnbfair** [comment]
I'm all for cleaning it up to make it more idiomatic :+1:

**Comment by pblasucci** [comment]
This has been attempted in PR #16
